name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name pelisnet

      - name: Build and push Docker image
        run: |
          docker build -t pelisnet.azurecr.io/pelisnet:latest .
          docker push pelisnet.azurecr.io/pelisnet:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: flask-webapp
          images: pelisnet.azurecr.io/pelisnet:latest
